pipeline {
    agent  any

    stages {

        stage('Prepare') {
            steps {
                checkout scm
                sh 'ls -la'
            }
        }


        stage('Run tests') {
            steps {


            sh '/Applications/apache-maen-3.6.1/bin/mvn test'
            }
        }


        stage('Generate report') {
            steps {
                cucumber buildStatus: 'UNSTABLE',
                        fileIncludePattern: '**/cucumber.json',
                        jsonReportDirectory: 'target',

            }
        }
    }
    }
